POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Fullstack Open Course",
    "author": "Matti Luukkainen",
    "url": "https://fullstackopen.com/en/",
    "likes": 7
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5
}