POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2ZmZmOTliYTAxZjQxMzk0NDZlNWNkNyIsImlhdCI6MTcyODA2NzYwMX0.--TDq_yZyV1JfEqFefoLzvlORiEri38yFw7o1jwL174

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsX211c2siLCJpZCI6IjY2ZmZjZjQzMjU0ZjNhMmY4ZjJiNmUxNSIsImlhdCI6MTcyODA3MDM4N30._ul2JlNNGYIuHG6E0LvKBgquqW_tyUBww3mHPAmjE-w

{
    "title": "TDD harms architecture",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "likes": 0
}