DELETE http://localhost:3003/api/blogs/670002a4aaab036617e97836
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsX211c2siLCJpZCI6IjY2ZmZjZjQzMjU0ZjNhMmY4ZjJiNmUxNSIsImlhdCI6MTcyODA3MDM4N30._ul2JlNNGYIuHG6E0LvKBgquqW_tyUBww3mHPAmjE-w